#! /bin/bash
# Copyright 2020 Alex Woroschilow (alex@fitbase.de)
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
FILE=`which "$0"`
APPDIR=`dirname "${FILE}"`

set -e

PATH=${PATH}:${APPDIR}/java/jdk-12.0.2/bin
PATH=${PATH}:${APPDIR}/application/bin
PATH=${PATH}:${APPDIR}/application/
export PATH=${PATH}

LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/java/jdk-12.0.2/lib
LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${APPDIR}/application/lib
export LD_LIBRARY_PATH

mkdir -p /tmp/mucommander/felix-cache

${APPDIR}/application/mucommander.sh $@

rm -rf /tmp/mucommander
